# Default values for snowflake-kafka-connect.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  connectrepository: turbonomic/snowflake-kafka-connect
  exporterrepository: turbonomic/exporter
  connecttag: latest
  exportertag: latest
  pullPolicy: IfNotPresent

resources:
   limits:
     memory: 2048Mi

service:
  type: ClusterIP
  port: 8083

env:
  - name: LOG_DIR
    value: /tmp/logs
  - name: KAFKA_OPTS
    value: >-
            -Dhttp.useProxy=true -Dhttps.useProxy=true
            -Dhttp.proxyHost=<proxyHost> -Dhttp.proxyPort=<proxyPort>
            -Dhttps.proxyHost=<proxyHostHTTPS> -Dhttps.proxyPort=<proxyPortHTTPS>
            -Dhttp.proxyUser=<ProxyUser> -Dhttp.proxyPassword=<ProxyPassword>
            -Dhttps.proxyUser=<ProxyUserHTTPS> -Dhttps.proxyPassword=<ProxyPasswordHTTPS>

nodeSelector: {}

tolerations: []

affinity: {}

args:
  mode: kafka
  loglevel: WARNING
