apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "snowflake-kafka-connect.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "snowflake-kafka-connect.name" . }}
    helm.sh/chart: {{ include "snowflake-kafka-connect.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "snowflake-kafka-connect.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "snowflake-kafka-connect.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
{{ toYaml .Values.env | indent 8 }}
        ports:
        - name: http
          containerPort: 8083
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /
            port: 8083
        resources:
        {{- toYaml .Values.resources | nindent 12 }}
        securityContext:
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL
        volumeMounts:
        - mountPath: /tmp
          name: snowflake-tmpfs0
      volumes:
      - name: snowflake-tmpfs0
        emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
